# Generated by Django 5.2 on 2025-08-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationrole',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member')], unique=True),
        ),
    ]
