# Generated by Django 5.2 on 2025-08-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_one_time_token',
            field=models.BooleanField(default=False),
        ),
    ]
