# Generated by Django 5.2 on 2025-09-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_token_is_one_time_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
